export const bookTips: Record<string, string[]> = {
  'Atomic Habits': [
    'Start with the 2-minute rule: shrink any new habit to a version that takes less than two minutes — if you want to read every night, start by opening the book. The goal is to show up, not to perform.',
    'Use habit stacking: anchor your new habit immediately after an existing one. "After I pour my morning coffee, I will write one sentence in my journal." The existing habit becomes the trigger.',
    'Make good habits obvious: redesign your environment so positive cues are visible. Place your running shoes by the door, put your vitamins next to your toothbrush, leave your guitar on a stand in plain sight.',
    'Make bad habits invisible: remove the triggers entirely. Delete the social media app, put the TV remote in a drawer, keep junk food out of the house. If it is not there, you cannot do it impulsively.',
    'Use implementation intentions: commit with a specific time and place — "I will meditate for 5 minutes at 7:00 AM in my bedroom." Vague intentions produce vague results.',
    'Track your habits with a simple calendar or app: mark an X each day. The visual chain of Xs creates a powerful motivation not to break the streak. Never miss twice — missing once is an accident, missing twice is a new bad habit starting.',
    'Focus on identity over outcomes: instead of "I want to lose weight", say "I am someone who takes care of their body." Every small action becomes a vote for the person you want to become.',
    'Use temptation bundling: pair a habit you dread with something you love. Only listen to your favourite podcast while exercising. Only watch your favourite show while folding laundry.',
    'Create an environment that makes good habits the path of least resistance. Meal-prep on Sunday so healthy food is the easy choice. Lay out your gym clothes the night before.',
    'Celebrate small wins immediately after completing a habit: a fist pump, a verbal "yes", a moment of satisfaction. The brain encodes behaviours that feel rewarding, making repetition automatic.',
  ],

  'Power': [
    'Master your emotions before every important interaction. A calm, unreadable face forces others to fill the silence with their own anxieties — emotional control is the foundation of strategic power.',
    'Control information deliberately: share only what serves your purpose, ask far more questions than you answer, and never reveal your full strategy until execution is unavoidable.',
    'Build a network of genuine allies by making each person feel uniquely valued. Remembered favours, specific compliments, and small acts of loyalty compound into durable influence.',
    'Study your opponents through their past behaviour under pressure, not their stated intentions. People reveal their true character when the stakes are high — watch the pattern, not the performance.',
    'Use timing as a weapon: patience accumulates force. Wait for the moment when your opponent is overextended, distracted, or desperate before making your decisive move.',
    'Create indispensability by developing rare skills or controlling access to key resources. The person others cannot easily replace occupies an unassailable position — become that person.',
    'Manage your reputation with the same care as a capital investment. Attack it proactively in any way you can, and respond to threats swiftly — a damaged reputation is hard to rebuild.',
    'Avoid unnecessary conflicts by refusing to react to every provocation. Most aggression is a test; by not engaging, you deny others the response they need to escalate.',
    'Maintain an air of mystery: never fully explain yourself or your plans. Incompleteness forces others to fill in the gaps with assumptions — often more impressive than the reality.',
    'Always have a backup plan so you never negotiate from desperation. Knowing you can walk away from any deal makes every conversation calmer and every position stronger.',
  ],

  "Can't Hurt Me": [
    'Apply the 40% rule: when your mind screams "stop", you have typically used only 40% of your real capacity. The next 60% is accessible only by refusing to quit at that first wall.',
    'Seek discomfort deliberately: schedule at least one physically or mentally hard challenge each week. Comfort is the enemy of growth — the more you avoid it, the smaller your world becomes.',
    'Practice the accountability mirror every morning: look yourself in the eye, state your goals out loud, and confront every excuse without mercy. Radical honesty with yourself is the starting point of all change.',
    'Callous your mind through accumulated repetition of hard things. Just as hands toughen with use, your mental resilience builds rep by rep — what broke you last year becomes routine today.',
    'Write down your excuses before dismissing them: seeing them on paper strips them of their emotional power and lets you dismantle each one with a plan of action rather than guilt.',
    'Use the 10-second count when you want to quit: stop, breathe, count slowly to ten, and recommit to just the next ten seconds. The mind can survive anything in ten-second increments.',
    'Build your identity through action, not affirmation. Do the hard thing first; the belief that you are the kind of person who does hard things will follow the evidence, not precede it.',
    'Build a mental "cookie jar" — a list of past sufferings and victories you can reach into whenever you need evidence that you have survived hard things before. Use it on demand.',
    'Establish non-negotiable daily micro-commitments: a fixed wake time, a made bed, the first difficult task completed before the phone is checked. Small disciplines maintain the identity you are building.',
    'Focus your energy entirely on what you can control — your preparation, your attitude, your effort — and release all attachment to outcomes that depend on external factors outside your influence.',
  ],

  'The Daily Stoic': [
    'Begin each morning with a Stoic question: "What is within my control today, and what is not?" Answering honestly sets the frame for a day spent on action rather than anxiety.',
    'Practice negative visualisation for 5 minutes daily: vividly imagine losing something you take for granted — your health, a relationship, your job. The exercise restores gratitude and reduces fear of loss.',
    'When facing an obstacle, ask "How can I use this?" instead of "Why is this happening to me?" Every setback contains a lesson or an opportunity if you approach it as a Stoic practitioner.',
    'Distinguish rigorously between what is "up to us" — our judgements, intentions, and responses — and what is not. Stop spending energy on the second category; pour it all into the first.',
    'Keep a Stoic journal each evening: write three things — what you did well, what you could improve, and one insight from the day. Review it weekly to track your character development.',
    'Pause before reacting to anger or frustration: count to ten, breathe slowly, then respond from reason rather than impulse. The Stoics called this the gap between stimulus and response — protect it.',
    'Live according to your values, not for the approval of others. Ask daily: "Am I acting as the person I want to be, or as the person others expect me to be?" The answer guides every decision.',
    'Treat every setback as a training exercise assigned specifically to build the strength you need most right now. Hardship is not happening to you; it is happening for you.',
    'Practice memento mori — briefly contemplate your own mortality each morning. This is not morbid; it is clarifying. It forces you to spend the day on what actually matters to you.',
    'Act for the common good: before any significant decision, ask how it affects the people around you. The Stoics believed virtue was inseparable from service to others and to community.',
  ],

  'The Rational Male': [
    'Understand the concept of sexual market value (SMV): your attractiveness is not fixed — it is built through fitness, status, skills, and confidence. Invest in all four consistently.',
    'Stop seeking external validation from women or from society: a man who needs approval signals low status. Develop your mission, your frame, and your standards independently.',
    'Maintain your frame in all relationships: your values, your reality, and your boundaries must be the foundation of every interaction. A man who loses his frame loses his respect.',
    'Embrace continuous self-improvement as a lifestyle, not a phase: the gym, reading, building income streams, and developing social skills are permanent pursuits, not temporary fixes to impress someone.',
    'Understand the nature of long-term attraction: comfort and familiarity alone do not sustain it. Maintain mystery, pursue your goals, and keep growing — stagnation is the enemy of attraction.',
    'Set and enforce clear boundaries without apology: know what you will and will not tolerate, communicate it once, and act accordingly. Boundaries respected signal strength; boundaries negotiated signal weakness.',
    'Develop an abundance mindset: scarcity thinking (fear of losing one option) leads to poor decisions. When you are building your life fully, no single outcome carries existential weight.',
    'Invest in your purpose above all else: a man with a mission is inherently more attractive and more fulfilled. Your work, your goals, and your legacy come before any relationship.',
    'Study social dynamics and human psychology dispassionately: understanding how incentives, status, and biology shape behaviour removes bitterness and replaces it with strategic clarity.',
    'Build financial independence as a non-negotiable foundation: economic dependence in any relationship inverts the power dynamic. Control your income, your expenses, and your long-term security.',
  ],
  'Die with Zero': [
    'Calculate your "life energy" per activity: estimate how much real enjoyment each recurring expense gives you relative to its cost. Cut ruthlessly what scores low and spend boldly on what scores high — experiences, not objects, dominate the top of this list.',
    'Time-bucket your life now: divide your remaining years into 5-year windows and write down what experiences belong in each one. Hiking belongs in your 30s, not your 70s. Waiting until "retirement" is often waiting until the experience is no longer physically or emotionally possible.',
    'Spend on experiences during your peak health years (roughly 30–60): your capacity to enjoy, travel, and engage fully is highest in these decades. Money spent on experiences at 45 delivers far more life value than the same money spent at 75.',
    'Give money to people while they can use it: if you plan to leave an inheritance, give it when recipients are in their 30s or 40s and can transform it into life experiences — not at the end when they are already financially established.',
    'Stop letting fear of the unknown make you hoard: most retirees consistently underspend because of anxiety about future costs. Model your actual spending needs with a financial planner. Evidence shows most people die with far more than they needed.',
    'Invest in memory dividends: experiences do not end when they end — they generate recurring returns in the form of memories, stories, and identity. A great trip at 35 pays emotional dividends for 40 years. A saved amount in a bank account pays nothing until spent.',
    'Use the rule of diminishing marginal utility for money: beyond a certain point (research suggests around $100K–$200K annual income), more money adds almost nothing to daily happiness. Optimise for experiences and time, not for accumulating beyond your real needs.',
    'Audit your deferred life plan: list all the things you are "saving for later." For each one, ask honestly: will I be able to enjoy this at 70 the same way I could at 45? If not, find a way to do it sooner — even a smaller version of it.',
    'Think in terms of net fulfilment, not net worth: the goal is to extract maximum life value from every dollar and year you have. Dying with a large estate is not financial success — it is evidence of unlived experiences and unmade memories.',
    'Schedule your peak experiences deliberately: do not wait for the right moment; it will not come spontaneously. Book the trip, plan the sabbatical, set the date. Experiences that remain in the "someday" category reliably never happen.',
  ],

  'The Book of Pook': [
    'Become, do not try to attract: stop performing for approval and focus entirely on becoming the man you want to be. Attraction is a natural by-product of genuine self-development — it cannot be manufactured through tactics alone.',
    'Kill the "nice guy" inside you: niceness used as a strategy to gain approval is not kindness — it is manipulation and it repels. Be direct, have opinions, disagree when you disagree. Authentic self-expression is more attractive than accommodating behaviour.',
    'Develop your purpose above all else: a man with a clear mission — a business, a craft, a cause — is intrinsically more compelling than one who makes a woman his primary focus. Let your purpose drive your life; let relationships be a complement, not the centre.',
    'Understand that women respond to who you are, not what you say: no line or technique substitutes for genuine confidence, status, and self-assurance. Invest your energy in building those qualities rather than in memorising scripts.',
    'Embrace rejection and failure as calibration: every "no" gives you feedback. Men who fear rejection become stagnant. Men who treat rejection as data keep improving. Make action a habit and let results inform you without defining you.',
    'Develop an abundant mentality: scarcity thinking — acting as if this woman is your last chance — telegraphs low value instantly. Cultivate options, invest in yourself, and approach any one interaction without desperation.',
    'Do not place women on a pedestal: idealising a woman before knowing her distorts your perception and creates neediness. See people clearly, as they are. Respect is earned through observation, not granted by default because of attraction.',
    'Lead in all things: plan the date, make the decision, set the frame. Not through domination, but through clarity and confidence. Men who wait for permission or seek constant approval signal low self-worth.',
    'Manage your emotions — do not suppress them: emotional volatility driven by a woman\'s behaviour signals that her approval controls you. Develop equanimity. Your emotional state should come from your values, not from external validation.',
    'Build yourself into someone you respect: the ultimate principle — become a man you are proud of independently of any relationship outcome. Physical fitness, financial autonomy, social competence, and personal integrity are not tools of seduction; they are the foundation of a meaningful life.',
  ],

  'How Bad Do You Want It?': [
    'Train your perception of effort, not just your body: the real limit in endurance is how hard an effort feels, not your muscles or lungs. Deliberately practise tolerating high perceived effort in training so it feels manageable in races.',
    'Use psyching-up techniques before hard efforts: a short, high-intensity self-talk routine, a power pose, or a motivational cue 30 seconds before a hard interval shifts your brain into a higher performance state.',
    'Develop a coping focus during suffering: instead of trying to distract yourself from pain, confront it directly with a plan — "this is hard and I am handling it." Athletes who cope outperform those who dissociate when effort peaks.',
    'Set process goals during competition, not outcome goals: focus entirely on controllable actions (cadence, form, breathing) rather than position or time. Process focus prevents panic and keeps performance stable under pressure.',
    'Build mental fitness through deliberate discomfort: add one workout per week that you intentionally do not want to do. The discomfort of doing it anyway is the training stimulus for mental toughness — not inspiration.',
    'Use the "10% more" rule when you want to quit: when your brain signals stop, ask whether you can give 10% more effort for just the next 30 seconds. Almost always the answer is yes — and that habit compounds into race-changing resilience.',
    'Practise emotional regulation, not emotional suppression: acknowledge fear, doubt, or pain without letting it dictate your pace. Name the feeling ("I feel terrible right now") and continue — naming reduces its power over behaviour.',
    'Study elite athletes not for their training plans but for their psychological responses: notice how champions reframe setbacks mid-race, slow down briefly to recalibrate, and make tactical decisions under exhaustion. Imitate the mindset, not just the mileage.',
    'Harness the power of competition and presence of others: train occasionally in groups or races even when solo training is easier. The brain lifts performance automatically in the presence of rivals — use this biological fact intentionally.',
    'Recover your motivation after a bad race by conducting a cold after-action review: separate what was physical, what was tactical, and what was psychological. Most bad races have a mental turning point — identify it precisely so you can rehearse a different response next time.',
  ],

  'How to Win Friends and Influence People': [
    'Show deep, genuine interest in others: ask about their work, their family, their passions — and listen more than you speak. People are won over by those who make them feel interesting, not those who are interesting themselves.',
    'Smile sincerely and consistently: a real smile signals warmth, safety, and goodwill. It is one of the cheapest and most powerful social investments you can make in any interaction.',
    "Remember and use people's names: repeat the name back in the conversation, write it down if you need to, associate it with a visual. To the person, their name is the sweetest sound in any language.",
    'Become a genuinely great listener: give your full attention, do not interrupt, and encourage others to keep talking by nodding and asking follow-up questions. Most people are desperate to be truly heard.',
    "Talk in terms of what the other person wants and values, not what you want. Before any important conversation, ask: 'What does this person care about, and how does my request relate to their interests?'",
    'Make the other person feel sincerely important: notice and acknowledge their contributions, expertise, or qualities specifically. Vague flattery is hollow; specific recognition is powerful.',
    'Replace criticism with curiosity: instead of pointing out what someone did wrong, ask questions that lead them to discover the issue themselves. People accept conclusions they reach on their own.',
    'Give honest and specific appreciation — not flattery, which is insincere, but genuine recognition of a real quality or action. The difference is that appreciation is true and flattery is manufactured.',
    "When you are wrong, admit it quickly and emphatically. Taking responsibility before someone attacks you disarms them completely and builds massive trust in your character.",
    "Let the other person feel the idea is theirs: ask questions that lead them toward your conclusion rather than stating it directly. Ownership of an idea produces far more commitment than agreement to someone else's.",
  ],
};
